package com.ivanisevic.sbg.api.service;

import com.ivanisevic.sbg.model.FilesUpdateRequestBody;
import com.ivanisevic.sbg.responses.FilesDownloadResponse;

import java.util.Map;

public interface CGCService {

    /**
     * Call CGC Api in order to fetch projects.
     * @param token - authorization token
     * @param queries - map of query parameters.
     */
    void listProjects(String token, Map<String, String> queries);

    /**
     * Call CGC Api in order to fetch files.
     * @param token - authorization token.
     * @param queries - map of query parameters.
     */
    void listFiles(String token, Map<String, String> queries);

    /**
     * Call CGC Api in order to fetch file statistic.
     * @param token - authorization token
     * @param queries - map of query parameters.
     * @param fileId - unique id of file generated by CGC.
     */
    void filesStat(String token, Map<String, String> queries, String fileId);

    /**
     * Updates specific file.
     * @param token - authorization token.
     * @param queries - map of query parameters.
     * @param fileId - unique id of file generated by CGC.
     * @param requestBody - object which contain differences for updating file.
     */
    void filesUpdate(String token, Map<String, String> queries, String fileId, FilesUpdateRequestBody requestBody);

    /**
     * Call CGC Api in order to fetch specific file download url.
     * @param token - authorization token
     * @param queries - map of query parameters
     * @param fileId - unique id of file generated by CGC.
     * @return URL for downloading file
     */
    FilesDownloadResponse getDownloadUrl(String token, Map<String, String> queries, String fileId);
}
